export enum Protocol {
  API = 'API',

  ESB = 'ESB',

  BATCH_FILE = 'BATCH_FILE',

  BATCH_FILE_MFT = 'BATCH_FILE_MFT',

  EVENT = 'EVENT',

  O2O_NODS = 'O2O_NODS',

  T24_API = 'T24_API',

  T24_NOTIF = 'T24_NOTIF',

  T24_ESB = 'T24_ESB',

  T24_DATA_SYNC_OUT = 'T24_DATA_SYNC_OUT',

  T24_DATA_SYNC_IN = 'T24_DATA_SYNC_IN',

  T24_FILE_IN = 'T24_FILE_IN',

  T24_TAP = 'T24_TAP',

  T24_BATCH_IN = 'T24_BATCH_IN',

  T24_BATCH_OUT = 'T24_BATCH_OUT',

  T24_DIRECT_IN = 'T24_DIRECT_IN',

  T24_DIRECT_JMS = 'T24_DIRECT_JMS',

  SOAP = 'SOAP',

  DEEPLINK = 'DEEPLINK',

  MQ = 'MQ',

  MANUAL = 'MANUAL',

  RPA = 'RPA',

  DIRECT_QUEUE_OVER_MQ = 'DIRECT_QUEUE_OVER_MQ',

  MAIL_FILE = 'MAIL_FILE',

  LINK = 'LINK',

  N_A = 'N_A',

  HTTP_DIRECT = 'HTTP_DIRECT',

  HTTP_REDIRECT = 'HTTP_REDIRECT',

  INDIRECT_THROUGH_CUSTOMER_BROWSER = 'INDIRECT_THROUGH_CUSTOMER_BROWSER',

  ETL_ODI = 'ETL_ODI',

  OUTLOOK_WIDGET = 'OUTLOOK_WIDGET',

  BATCH_FILE_THROUGH_IMFT = 'BATCH_FILE_THROUGH_IMFT',

  NATIVE = 'NATIVE',

  FILE = 'FILE',

  NAS = 'NAS',

  FILE_ZIP_MFT_NAS = 'FILE_ZIP_MFT_NAS',
}
