export enum SoftwareType {
  ON_PREMISE_COTS = 'ON_PREMISE_COTS',

  ON_PREMISE_CUSTOM = 'ON_PREMISE_CUSTOM',

  CLOUD_CUSTOM = 'CLOUD_CUSTOM',

  CLOUD_SAAS = 'CLOUD_SAAS',

  CLOUD_THIRD_PARTY = 'CLOUD_THIRD_PARTY',

  ON_PREMISE_EXTERNAL_LIBRARY = 'ON_PREMISE_EXTERNAL_LIBRARY',
}
